nextcloud_root: "/data/{{ ansible_role_name }}"
nextcloud_domain: "cloud.{{ network.domain | ansible.builtin.mandatory }}"

nextcloud_upgrade_timeout: 3m

# renovate: docker=nextcloud
nextcloud_version: 33.0.6-apache

nextcloud_mcp_clients: []
nextcloud_mcp_client_list: >-
  {{
    nextcloud_mcp_clients |
    map(attribute = 'client_id') |
    zip(nextcloud_mcp_clients |
      map(attribute = 'callback_url') |
      map('default', '')) |
    map('select') |
    map('join', '|')
  }}

nextcloud_mcp_management_clients: []
nextcloud_mcp_management_client_list: >-
  {{
    nextcloud_mcp_management_clients |
    map(attribute = 'client_id')
  }}
