#!/usr/bin/env bash

# Script to disable dependencies between roles to speed up development.
#
# This script will ignore and remove all git-tracked files matching
# roles/**/meta/main.yml.
#
# Ignoring is done with `git update-index --skip-worktree` which will make git
# temporarily ignore any change to these files (content-wise and including
# removal).
#
# Undo by running this script again with any argument, e.g. `off`.
# After that, you might want to git {checkout,restore} those files.

set -euo pipefail

root="$(git rev-parse --show-toplevel)"
pushd "$root" > /dev/null

if (($# > 0)); then
  mapfile -t ignored < <(git ls-files -v |
                          grep '^S' |
                          cut -d ' ' -f 2- |
                          grep '^roles' |
                          grep '/meta/main.yml')

  for file in "${ignored[@]}"; do
    printf 'Unignoring %s\n' "$file"
    git update-index --no-skip-worktree -- "$file"
  done

  exit
fi

mapfile -t meta_files < <(git ls-files |
                          grep '^roles' |
                          grep '/meta/main.yml')

for file in "${meta_files[@]}"; do
  printf 'Ignoring and removing %s\n' "$file"
  git update-index --skip-worktree -- "$file"

  # File might have been removed manually.
  rm -- "$file" || true
done
