- name: Register ACME account
  community.proxmox.proxmox_acme_account:
    name: "{{ pve_acme_account_id }}"
    contact: "{{ pve_acme_account_email }}"
    directory: https://acme-v02.api.letsencrypt.org/directory

- name: Configure ACME plugin
  community.proxmox.proxmox_acme_plugin_dns:
    name: desec
    plugin: desec
    data:
      DEDYN_TOKEN: "{{ desec_acme_token }}"
    validation_delay: 120

- name: Order ACME certificate
  community.proxmox.proxmox_acme_certificate:
    node_name: "{{ ansible_facts.hostname }}"
    account: "{{ pve_acme_account_id }}"
    domains:
      - domain: "{{ pve_fqdn }}"
        plugin: desec
