- name: Restart frigate service
  when: frigate_started is not changed
  ansible.builtin.systemd:
    name: frigate.service
    state: restarted

- name: Reload frigate service
  when: frigate_started is not changed
  ansible.builtin.systemd:
    name: frigate.service
    state: reloaded
