node_exporter_extras:
  - role: prometheus.prometheus.smartctl_exporter
    port: >-
      {{
        ('//' ~ smartctl_exporter_web_listen_address) |
        ansible.builtin.urlsplit('port')
      }}
    job: smartctl
  - role: prometheus.prometheus.ipmi_exporter
    port: >-
      {{
        ('//' ~ ipmi_exporter_web_listen_address) |
        ansible.builtin.urlsplit('port')
      }}
    job: ipmi
  - role: pve_exporter
    port: 9221
    job: pve
  - role: zfs_exporter
    port: 9134
    job: zfs
