zfs_snapshot_datasets:
  - dataset: "rpool/data/vm-{{ hostvars.nest.proxmox.id }}-disk-0"
    settings: |
      use_template = vm_volume
  - dataset: "rpool/data/vm-{{ hostvars.nest.proxmox.id }}-disk-1"
    settings: |
      use_template = vm_volume

  - dataset: tank/freshrss
    settings: |
      {{ zfs_snapshot_default_dataset_settings }}
      process_children_only = yes

  - dataset: tank/grossweber/banking
    settings: |
      {{ zfs_snapshot_default_dataset_settings }}
      process_children_only = yes

  - dataset: tank/harbor
    settings: |
      {{ zfs_snapshot_default_dataset_settings }}
      process_children_only = yes

  - dataset: tank/immich/app
  - dataset: tank/immich/postgres

  - dataset: tank/nextcloud/app
  - dataset: tank/nextcloud/mariadb

  - dataset: tank/tandoor
    settings: |
      {{ zfs_snapshot_default_dataset_settings }}
      process_children_only = yes

  - dataset: tank/vaultwarden
    settings: |
      {{ zfs_snapshot_default_dataset_settings }}
      process_children_only = yes
