zfs_snapshot_proxmox_datasets_on_host: >-
  {{
    groups['all'] |
    map('ansible.builtin.extract', hostvars) |
    selectattr('zfs_datasets', 'defined') |
    selectattr('proxmox.host', 'defined') |
    selectattr('proxmox.host', 'equalto', inventory_hostname) |
    map(attribute = 'zfs_datasets') |
    map('ansible.builtin.dict2items', key_name = "dataset") |
    ansible.builtin.flatten |
    selectattr('value.snapshot', 'defined') |
    ansible.builtin.json_query('[].{ dataset: dataset, settings: value.snapshot }')
  }}

zfs_snapshot_datasets: []

zfs_snapshot_datasets_combined: >-
  {{
    (
      zfs_snapshot_proxmox_datasets_on_host +
      zfs_snapshot_datasets
    ) |
    sort(attribute = 'dataset')
  }}

zfs_snapshot_default_dataset_settings: ""

zfs_snapshot_sanoid_templates: |
  [template_vm_volume]
    frequently = 0
    hourly = 24
    daily = 14
    weekly = 0
    monthly = 0
    yearly = 0

    autosnap = yes
    autoprune = yes

  [template_default]
    frequently = 0
    hourly = 24
    daily = 30
    weekly = 4
    monthly = 3
    yearly = 0

    autosnap = yes
    autoprune = yes
