- name: Include OS-specific variables
  ansible.builtin.include_vars:
    file: "{{ file }}"
  with_first_found:
    - "{{ ansible_facts.distribution }}.yml"
    - "{{ ansible_facts.os_family }}.yml"
  loop_control:
    loop_var: file

- name: Ensure backup healthcheck exists
  ansible.builtin.import_tasks:
    file: healthcheck.yml
  vars:
    healthcheck_name: system
    healthcheck_tags:
      - "site:{{ site }}"
      - "host:{{ inventory_hostname }}"

- name: Install borgmatic
  ansible.builtin.include_role:
    name: borgbase.ansible_role_borgbackup
    # Expose vars, we need _borgbackup_config.name for validation.
    public: true
  vars:
    borgbackup_install: >-
      {{
        borgmatic_borgbackup_install |
        combine(borgmatic_borgbackup_install_override | default({}), recursive=true)
      }}
    borgbackup_timer: "{{ borgmatic_borgbackup_timer }}"
    borgbackup_ssh: "{{ borgmatic_borgbackup_ssh }}"
    borgbackup_config: "{{ borgmatic_borgbackup_config }}"

- name: Validate config file
  ansible.builtin.command:
    argv:
      - borgmatic
      - --config
      - "/etc/borgmatic/{{ _borgbackup_config.name }}"
      - config
      - validate
  changed_when: false

- name: Ensure /etc/borgmatic.d exists
  ansible.builtin.file:
    path: /etc/borgmatic.d
    state: directory
    owner: 0
    group: 0
    mode: "700"

- name: OS-dependent post-installation
  ansible.builtin.include_tasks:
    file: "{{ file }}"
  with_first_found:
    - "postinstall-{{ ansible_facts.distribution }}.yml"
    - "postinstall-{{ ansible_facts.os_family }}.yml"
  loop_control:
    loop_var: file

- name: Start borgmatic timer
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: borgmatic.timer
    daemon_reload: true
  register: borgmatic_timer_started
