- name: Copy templates
  ansible.builtin.import_tasks:
    file: copy-templates.yml
  vars:
    directory: ../templates
    target: "{{ inverter_influxdb_root }}"
    notify_: Restart inverter-influxdb service
    files:
      app/config.yml.j2:
        mode: "600"

- name: Update docker-compose images
  ansible.builtin.import_tasks:
    file: docker-compose-update.yml
  vars:
    directory: "{{ inverter_influxdb_root }}"
    pull: true
    build: true
    notify_: Restart inverter-influxdb service

- name: Install systemd units
  ansible.builtin.import_tasks: systemd-install-units.yml
  vars:
    directory: "{{ inverter_influxdb_root }}/systemd"
    local_units: templates/systemd
    notify_: Restart inverter-influxdb service

- name: Start service
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: "{{ item }}"
    daemon_reload: true
  loop: "{{ systemd_units_autostart }}"
  register: inverter_influxdb_started
