systemd_networkd_netdev:
  ccu:
    - NetDev:
        - Description: Required for CCU host access.
        - Name: ccu
        - Kind: macvlan

    - MACVLAN:
        - Mode: bridge

  iobroker:
    - NetDev:
        - Description: Required for ioBroker host access.
        - Name: iobroker
        - Kind: macvlan

    - MACVLAN:
        - Mode: bridge

systemd_networkd_network:
  enp6s18:
    - Match:
        - Name: "{{ interfaces.lan.device }}"
    - Network:
        - DHCP: false
        - Address: >-
            {{
              (interfaces.lan.ip4.address ~ '/' ~ interfaces.lan.ip4.prefix) |
              ansible.utils.ipaddr('host/prefix')
            }}
        - Address: >-
            {{
              (interfaces.lan.ip6.address ~ '/' ~ interfaces.lan.ip6.prefix) |
              ansible.utils.ipaddr('host/prefix')
            }}
        - DNS: "{{ interfaces.lan.ip4.dns }}"
        - DNS: "{{ interfaces.lan.ip6.dns }}"
        - DNSDefaultRoute: true
        - Domains: "{{ dns.search_domains | join(' ') }}"
        - MulticastDNS: true

        - IPv6LinkLocalAddressGenerationMode: stable-privacy
        - IPv6AcceptRA: false

        - Gateway: "{{ network_gateway.ip4 }}"
        - Gateway: "{{ network_gateway.ip6 }}"

        - MACVLAN: ccu
        - MACVLAN: iobroker

  ccu:
    - Match:
        - Name: ccu

    - Network:
        - Description: Required for CCU host access.
        - Address: "{{ network.ip4 | ansible.utils.nthhost(241) | ansible.utils.ipaddr('host/prefix') }}"
        - LinkLocalAddressing: false
        - IPv6AcceptRA: false
        - ConfigureWithoutCarrier: true

    - Route:
        - Destination: "{{ ccu_ip4 }}"

  iobroker:
    - Match:
        - Name: iobroker

    - Network:
        - Description: Required for ioBroker host access.
        - Address: "{{ network.ip4 | ansible.utils.nthhost(243) | ansible.utils.ipaddr('host/prefix') }}"
        - LinkLocalAddressing: false
        - IPv6AcceptRA: false
        - ConfigureWithoutCarrier: true

    - Route:
        - Destination: "{{ iobroker_ip4 }}"
