# renovate: docker=ghcr.io/actions/actions-runner
github_runner_version: 2.335.1

github_runner_instance_from_basic_vars_yaml: |
  {{ github_runner_name | ansible.builtin.mandatory }}:
    url: {{ github_runner_url | ansible.builtin.mandatory }}
    token: {{ github_runner_token | ansible.builtin.mandatory }}

github_runner_instances: >-
  {{
    github_runner_instance_from_basic_vars_yaml |
    ansible.builtin.from_yaml |
    default({}, true)
  }}
