#!/bin/sh

set -e

FILE=/opt/adguardhome/conf/AdGuardHome.yaml

if [ ! -f $FILE ]; then
  printf 'Waiting for config to be finished'

  wget -S -O /dev/null localhost
  nslookup localhost localhost
  exit 0
fi

HTTP_ADDRESS="$(grep '^  address:' "$FILE" | cut -f 4 -d ' ')"
HTTP_HOST="${HTTP_ADDRESS%%:*}"
[ "$HTTP_HOST" = 0.0.0.0 ] && HTTP_HOST=localhost
HTTP_PORT="${HTTP_ADDRESS#*:}"

DNS_PORT="$(grep '^  port:' "$FILE" | cut -f 4 -d ' ')"

wget -S -O /dev/null "$HTTP_HOST:$HTTP_PORT"
nslookup localhost "localhost:$DNS_PORT"
