node_exporter_candidates:
  - enabled: true
    role: prometheus.prometheus.node_exporter
    firewalld_service: prometheus-node-exporter
    port: >-
      {{
        ('//' ~ node_exporter_web_listen_address) |
        ansible.builtin.urlsplit('port')
      }}
    job: node

  - enabled: "{{ 'docker0' in ansible_facts.interfaces }}"
    role: prometheus.prometheus.cadvisor
    firewalld_service: cadvisor
    port: "{{ cadvisor_port }}"
    job: cadvisor

  - enabled: >-
      {{
        ansible_facts.service_mgr == 'systemd' and
        'synoboot' not in ansible_facts.devices
      }}
    role: prometheus.prometheus.systemd_exporter
    firewalld_service: systemd-exporter
    port: >-
      {{
        ('//' ~ systemd_exporter_web_listen_address) |
        ansible.builtin.urlsplit('port')
      }}
    job: systemd

node_exporter_dynamic_roles: >-
  {{
    node_exporter_candidates |
    selectattr('enabled') |
    list
  }}

node_exporter_extras: []

node_exporter_roles: >-
  {{
    node_exporter_dynamic_roles +
    node_exporter_extras
  }}
