node_exporter_candidates:
  - enabled: true
    value:
      role: prometheus.prometheus.node_exporter
      firewalld_service: prometheus-node-exporter
      port: 9100
      job: node

  - enabled: "{{ 'docker0' in ansible_facts.interfaces }}"
    value:
      role: prometheus.prometheus.cadvisor
      firewalld_service: cadvisor
      port: "{{ cadvisor_port }}"
      job: cadvisor

  - enabled: >-
      {{
        ansible_facts.service_mgr == 'systemd' and
        'synoboot' not in ansible_facts.devices
      }}
    value:
      role: prometheus.prometheus.systemd_exporter
      firewalld_service: systemd-exporter
      port: 9558
      job: systemd

node_exporter_dynamic_roles: >-
  {{
    node_exporter_candidates |
    selectattr('enabled') |
    map(attribute = 'value') |
    list
  }}

node_exporter_extras: []

node_exporter_roles: >-
  {{
    node_exporter_dynamic_roles +
    node_exporter_extras
  }}
