- name: Ensure backup healthcheck exists
  ansible.builtin.import_tasks:
    file: healthcheck.yml
  vars:
    healthcheck_name: "{{ ansible_role_name }}"
    healthcheck_tags:
      - "site:{{ site }}"
      - "host:{{ inventory_hostname }}"

- name: Copy default templates
  ansible.builtin.import_tasks: copy-templates.yml
  vars:
    directory: ../templates
    target: "{{ prometheus_root }}"
    notify_: Reload prometheus service
    files:
      systemd/**:
        notify_: Restart prometheus service
      docker-compose.yaml.j2:
        owner: 0
        group: 0
        mode: '640'
      app/conf.d/**:
        notify_: Reload Prometheus configuration
      app/data:
        owner: 65534
        group: 65534
      backup.j2:
        mode: '750'
        owner: 0
        group: 0
      restore.j2:
        mode: '750'
        owner: 0
        group: 0

- name: Copy templates for {{ inventory_hostname }}
  when: directory | length > 0
  ansible.builtin.include_tasks:
    file: copy-templates.yml
  vars:
    paths:
      - "{{ playbook_dir }}/templates/{{ ansible_role_name }}/{{ inventory_hostname }}"
    directory: "{{ lookup('ansible.builtin.first_found', paths, skip=true) }}"
    target: "{{ prometheus_root }}"
    notify_: Reload prometheus service
    files:
      app/conf.d/**:
        notify_: Reload Prometheus configuration

- name: Ensure jq is installed (used for backup script)
  ansible.builtin.package:
    name: jq
    state: present

- name: Update docker-compose images
  ansible.builtin.import_tasks:
    file: docker-compose-update.yml
  vars:
    directory: "{{ prometheus_root }}"
    pull: true
    build: true
    notify_: Reload prometheus service

- name: Restore from backup if requested
  when: restore is defined
  ansible.builtin.import_tasks:
    file: restore.yml
  vars:
    restore_target_dir: "{{ prometheus_root }}"

- name: Symlink systemd unit
  ansible.builtin.file:
    state: link
    src: "{{ prometheus_root }}/systemd/{{ ansible_role_name }}.service"
    path: "/etc/systemd/system/{{ ansible_role_name }}.service"
    force: true
  notify: Restart prometheus service

- name: Start systemd unit
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: "{{ ansible_role_name }}.service"
    daemon_reload: true
  register: prometheus_started

- name: Symlink backup configuration
  ansible.builtin.file:
    state: link
    src: "{{ prometheus_root }}/backup.yaml"
    path: "/etc/borgmatic.d/{{ ansible_role_name }}.yaml"

- name: Register with loadbalancer
  ansible.builtin.import_tasks:
    file: register-with-loadbalancer.yml
