tasmota_config_mqtt_host: mqtt
tasmota_config_mqtt_port: 1883

tasmota_config_mqtt_topic: "{{ network_name }}"

tasmota_config_mqtt_full_topic: >-
  {{
    site
  }}/{{
    tasmota_config_room | lower | replace(' ', '-')
  }}/{{
    tasmota_config_function
  }}/%prefix%/%topic%/

# Suffix because of https://github.com/arendst/Tasmota/issues/9282
tasmota_config_mqtt_client: "{{ tasmota_config_mqtt_topic }}-client"

# Device function, e.g. power, lights, climate.
tasmota_config_function: power

tasmota_config_device_index: >-
  #{{ network_name | ansible.builtin.regex_search('(?<=-)\d+$') }}

tasmota_config_device_name: >-
  {{ tasmota_config_room }}{{
    '' if tasmota_config_installation_location | default('', true) | length == 0
    else ' ' ~ tasmota_config_installation_location
  }}
  {{ tasmota_config_purpose }}

# Used by the Transform Tasmota Data script in ioBroker.
# https://github.com/agross/iobroker-scripts/blob/master/home/Automation/Oneshot/Transform_Tasmota_Data.ts
# 0: <optional Lovelace icon>
# 1: <optional Lovelace name>.
tasmota_config_friendly_name: []
