frigate_root: "/data/{{ ansible_role_name }}"

# renovate: github-releases=AlexxIT/go2rtc
frigate_go2rtc_release_version: v1.9.14
frigate_go2rtc_release_file: go2rtc_linux_amd64

frigate_camera_user: frigate

frigate_mqtt_topic_prefix: "{{ site }}/frigate"

# renovate: github-releases=dbro/frigate-detector-edgetpu-yolo9
frigate_yolov9_release_version: v1.5
frigate_yolov9_release_file: yolov9-s-relu6-tpumax_512_int8_edgetpu.tflite
frigate_yolov9_dimension: 512
